{% set name = "mols2grid" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mols2grid-{{ version }}.tar.gz
  sha256: 3a6cadd73c8ccd79b7da978eb2fe2416153495239852039d76465c7c18d63b07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2
    - pandas
    - python >=3.6
    - rdkit >=2020.03.1

test:
  imports:
    - mols2grid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cbouy/mols2grid
  summary: Chemical viewer for 2D structures of small molecules
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
