{% set name = "mols2grid" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mols2grid-{{ version }}.tar.gz
  sha256: c1038df3f906ddce3731fac128e76dd7a871cfda576e63ff5ffbb5700e4ba189

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jinja2>=2.11.0
    - pandas
    - python >=3.7
    - rdkit >=2020.03.1

test:
  imports:
    - mols2grid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cbouy/mols2grid
  summary: Chemical viewer for 2D structures of small molecules
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
